services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
  weather_app:
    build: .
    container_name: weather_app
    ports:
      - "50051:50051"
      - "8050:8050"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo_data:
