# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weather_microservice.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'weather_microservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aweather_microservice.proto\x12\x14weather_microservice\"\x1e\n\x0eWeatherRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"\xed\x02\n\x0fWeatherResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x30\n\x05\x63oord\x18\x03 \x01(\x0b\x32!.weather_microservice.Coordinates\x12\x13\n\x0btemperature\x18\x04 \x01(\x01\x12\x12\n\nfeels_like\x18\x05 \x01(\x01\x12\x10\n\x08temp_min\x18\x06 \x01(\x01\x12\x10\n\x08temp_max\x18\x07 \x01(\x01\x12\x10\n\x08pressure\x18\x08 \x01(\x05\x12\x10\n\x08humidity\x18\t \x01(\x05\x12\x12\n\nwind_speed\x18\n \x01(\x01\x12\x10\n\x08wind_deg\x18\x0b \x01(\x05\x12\x11\n\twind_gust\x18\x0c \x01(\x01\x12\x16\n\x0emain_condition\x18\r \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x0e \x01(\t\x12\x0f\n\x07rain_1h\x18\x0f \x01(\x01\x12\x0e\n\x06\x63louds\x18\x10 \x01(\x05\x12\x11\n\ttimestamp\x18\x11 \x01(\x03\"\'\n\x0b\x43oordinates\x12\x0b\n\x03lon\x18\x01 \x01(\x01\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x32k\n\x0eWeatherService\x12Y\n\nGetWeather\x12$.weather_microservice.WeatherRequest\x1a%.weather_microservice.WeatherResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weather_microservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WEATHERREQUEST']._serialized_start=52
  _globals['_WEATHERREQUEST']._serialized_end=82
  _globals['_WEATHERRESPONSE']._serialized_start=85
  _globals['_WEATHERRESPONSE']._serialized_end=450
  _globals['_COORDINATES']._serialized_start=452
  _globals['_COORDINATES']._serialized_end=491
  _globals['_WEATHERSERVICE']._serialized_start=493
  _globals['_WEATHERSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
